name: Build - Module

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-build.yaml@main
    with:
      packages: codbex-hermes-data-sample
    secrets: inherit
  
