name: Release - Module

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-hermes-data-sample
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-hermes-data-sample - ${{ inputs.release-version }}
  
        Customer Relationship Management Data Sample
  
        ## Installation
  
        ```
        npm install @codbex/codbex-hermes-data-sample@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - N/A
    secrets: inherit